/*
 * File:           C:\Users\perry\Documents\GitHub\EasyDSP\device_firmware\sigma_studio_project\export\easydsp_IC_1_PARAM.h
 *
 * Created:        Monday, July 24, 2023 7:13:49 PM
 * Description:    easydsp:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2023 Analog Devices, Inc. All rights reserved.
 */
#ifndef __EASYDSP_IC_1_PARAM_H__
#define __EASYDSP_IC_1_PARAM_H__


/* Module input1_eq - Medium Size Eq*/
#define MOD_INPUT1_EQ_COUNT                            25
#define MOD_INPUT1_EQ_DEVICE                           "IC1"
#define MOD_INPUT1_EQ_ALG0_STAGE0_B0_ADDR              0
#define MOD_INPUT1_EQ_ALG0_STAGE0_B0_FIXPT             0x00800000
#define MOD_INPUT1_EQ_ALG0_STAGE0_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT1_EQ_ALG0_STAGE0_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE0_B1_ADDR              1
#define MOD_INPUT1_EQ_ALG0_STAGE0_B1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE0_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE0_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE0_B2_ADDR              2
#define MOD_INPUT1_EQ_ALG0_STAGE0_B2_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE0_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE0_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE0_A0_ADDR              3
#define MOD_INPUT1_EQ_ALG0_STAGE0_A0_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE0_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE0_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE0_A1_ADDR              4
#define MOD_INPUT1_EQ_ALG0_STAGE0_A1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE0_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE0_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE1_B0_ADDR              5
#define MOD_INPUT1_EQ_ALG0_STAGE1_B0_FIXPT             0x00800000
#define MOD_INPUT1_EQ_ALG0_STAGE1_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT1_EQ_ALG0_STAGE1_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE1_B1_ADDR              6
#define MOD_INPUT1_EQ_ALG0_STAGE1_B1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE1_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE1_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE1_B2_ADDR              7
#define MOD_INPUT1_EQ_ALG0_STAGE1_B2_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE1_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE1_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE1_A0_ADDR              8
#define MOD_INPUT1_EQ_ALG0_STAGE1_A0_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE1_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE1_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE1_A1_ADDR              9
#define MOD_INPUT1_EQ_ALG0_STAGE1_A1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE1_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE1_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE2_B0_ADDR              10
#define MOD_INPUT1_EQ_ALG0_STAGE2_B0_FIXPT             0x00800000
#define MOD_INPUT1_EQ_ALG0_STAGE2_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT1_EQ_ALG0_STAGE2_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE2_B1_ADDR              11
#define MOD_INPUT1_EQ_ALG0_STAGE2_B1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE2_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE2_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE2_B2_ADDR              12
#define MOD_INPUT1_EQ_ALG0_STAGE2_B2_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE2_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE2_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE2_A0_ADDR              13
#define MOD_INPUT1_EQ_ALG0_STAGE2_A0_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE2_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE2_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE2_A1_ADDR              14
#define MOD_INPUT1_EQ_ALG0_STAGE2_A1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE2_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE2_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE3_B0_ADDR              15
#define MOD_INPUT1_EQ_ALG0_STAGE3_B0_FIXPT             0x00800000
#define MOD_INPUT1_EQ_ALG0_STAGE3_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT1_EQ_ALG0_STAGE3_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE3_B1_ADDR              16
#define MOD_INPUT1_EQ_ALG0_STAGE3_B1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE3_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE3_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE3_B2_ADDR              17
#define MOD_INPUT1_EQ_ALG0_STAGE3_B2_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE3_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE3_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE3_A0_ADDR              18
#define MOD_INPUT1_EQ_ALG0_STAGE3_A0_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE3_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE3_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE3_A1_ADDR              19
#define MOD_INPUT1_EQ_ALG0_STAGE3_A1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE3_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE3_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE4_B0_ADDR              20
#define MOD_INPUT1_EQ_ALG0_STAGE4_B0_FIXPT             0x00800000
#define MOD_INPUT1_EQ_ALG0_STAGE4_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT1_EQ_ALG0_STAGE4_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE4_B1_ADDR              21
#define MOD_INPUT1_EQ_ALG0_STAGE4_B1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE4_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE4_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE4_B2_ADDR              22
#define MOD_INPUT1_EQ_ALG0_STAGE4_B2_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE4_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE4_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE4_A0_ADDR              23
#define MOD_INPUT1_EQ_ALG0_STAGE4_A0_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE4_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE4_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT1_EQ_ALG0_STAGE4_A1_ADDR              24
#define MOD_INPUT1_EQ_ALG0_STAGE4_A1_FIXPT             0x00000000
#define MOD_INPUT1_EQ_ALG0_STAGE4_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT1_EQ_ALG0_STAGE4_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module input2_eq - Medium Size Eq*/
#define MOD_INPUT2_EQ_COUNT                            25
#define MOD_INPUT2_EQ_DEVICE                           "IC1"
#define MOD_INPUT2_EQ_ALG0_STAGE0_B0_ADDR              25
#define MOD_INPUT2_EQ_ALG0_STAGE0_B0_FIXPT             0x00800000
#define MOD_INPUT2_EQ_ALG0_STAGE0_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT2_EQ_ALG0_STAGE0_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE0_B1_ADDR              26
#define MOD_INPUT2_EQ_ALG0_STAGE0_B1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE0_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE0_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE0_B2_ADDR              27
#define MOD_INPUT2_EQ_ALG0_STAGE0_B2_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE0_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE0_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE0_A0_ADDR              28
#define MOD_INPUT2_EQ_ALG0_STAGE0_A0_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE0_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE0_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE0_A1_ADDR              29
#define MOD_INPUT2_EQ_ALG0_STAGE0_A1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE0_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE0_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE1_B0_ADDR              30
#define MOD_INPUT2_EQ_ALG0_STAGE1_B0_FIXPT             0x00800000
#define MOD_INPUT2_EQ_ALG0_STAGE1_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT2_EQ_ALG0_STAGE1_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE1_B1_ADDR              31
#define MOD_INPUT2_EQ_ALG0_STAGE1_B1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE1_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE1_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE1_B2_ADDR              32
#define MOD_INPUT2_EQ_ALG0_STAGE1_B2_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE1_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE1_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE1_A0_ADDR              33
#define MOD_INPUT2_EQ_ALG0_STAGE1_A0_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE1_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE1_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE1_A1_ADDR              34
#define MOD_INPUT2_EQ_ALG0_STAGE1_A1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE1_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE1_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE2_B0_ADDR              35
#define MOD_INPUT2_EQ_ALG0_STAGE2_B0_FIXPT             0x00800000
#define MOD_INPUT2_EQ_ALG0_STAGE2_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT2_EQ_ALG0_STAGE2_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE2_B1_ADDR              36
#define MOD_INPUT2_EQ_ALG0_STAGE2_B1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE2_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE2_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE2_B2_ADDR              37
#define MOD_INPUT2_EQ_ALG0_STAGE2_B2_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE2_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE2_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE2_A0_ADDR              38
#define MOD_INPUT2_EQ_ALG0_STAGE2_A0_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE2_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE2_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE2_A1_ADDR              39
#define MOD_INPUT2_EQ_ALG0_STAGE2_A1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE2_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE2_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE3_B0_ADDR              40
#define MOD_INPUT2_EQ_ALG0_STAGE3_B0_FIXPT             0x00800000
#define MOD_INPUT2_EQ_ALG0_STAGE3_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT2_EQ_ALG0_STAGE3_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE3_B1_ADDR              41
#define MOD_INPUT2_EQ_ALG0_STAGE3_B1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE3_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE3_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE3_B2_ADDR              42
#define MOD_INPUT2_EQ_ALG0_STAGE3_B2_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE3_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE3_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE3_A0_ADDR              43
#define MOD_INPUT2_EQ_ALG0_STAGE3_A0_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE3_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE3_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE3_A1_ADDR              44
#define MOD_INPUT2_EQ_ALG0_STAGE3_A1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE3_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE3_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE4_B0_ADDR              45
#define MOD_INPUT2_EQ_ALG0_STAGE4_B0_FIXPT             0x00800000
#define MOD_INPUT2_EQ_ALG0_STAGE4_B0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT2_EQ_ALG0_STAGE4_B0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE4_B1_ADDR              46
#define MOD_INPUT2_EQ_ALG0_STAGE4_B1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE4_B1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE4_B1_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE4_B2_ADDR              47
#define MOD_INPUT2_EQ_ALG0_STAGE4_B2_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE4_B2_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE4_B2_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE4_A0_ADDR              48
#define MOD_INPUT2_EQ_ALG0_STAGE4_A0_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE4_A0_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE4_A0_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT2_EQ_ALG0_STAGE4_A1_ADDR              49
#define MOD_INPUT2_EQ_ALG0_STAGE4_A1_FIXPT             0x00000000
#define MOD_INPUT2_EQ_ALG0_STAGE4_A1_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT2_EQ_ALG0_STAGE4_A1_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Mg1 - Signal Merger*/
#define MOD_MG1_COUNT                                  1
#define MOD_MG1_DEVICE                                 "IC1"
#define MOD_MG1_SINGLECTRLMIXER19401_ADDR              50
#define MOD_MG1_SINGLECTRLMIXER19401_FIXPT             0x00400000
#define MOD_MG1_SINGLECTRLMIXER19401_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_MG1_SINGLECTRLMIXER19401_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module output1_select - Mono Switch Nx1*/
#define MOD_OUTPUT1_SELECT_COUNT                       1
#define MOD_OUTPUT1_SELECT_DEVICE                      "IC1"
#define MOD_OUTPUT1_SELECT_MONOSWSLEW_ADDR             51
#define MOD_OUTPUT1_SELECT_MONOSWSLEW_FIXPT            0x00000000
#define MOD_OUTPUT1_SELECT_MONOSWSLEW_VALUE            SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_OUTPUT1_SELECT_MONOSWSLEW_TYPE             SIGMASTUDIOTYPE_INTEGER

/* Module output2_select - Mono Switch Nx1*/
#define MOD_OUTPUT2_SELECT_COUNT                       1
#define MOD_OUTPUT2_SELECT_DEVICE                      "IC1"
#define MOD_OUTPUT2_SELECT_MONOSWSLEW_ADDR             52
#define MOD_OUTPUT2_SELECT_MONOSWSLEW_FIXPT            0x00000000
#define MOD_OUTPUT2_SELECT_MONOSWSLEW_VALUE            SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_OUTPUT2_SELECT_MONOSWSLEW_TYPE             SIGMASTUDIOTYPE_INTEGER

/* Module output3_select - Mono Switch Nx1*/
#define MOD_OUTPUT3_SELECT_COUNT                       1
#define MOD_OUTPUT3_SELECT_DEVICE                      "IC1"
#define MOD_OUTPUT3_SELECT_MONOSWSLEW_ADDR             53
#define MOD_OUTPUT3_SELECT_MONOSWSLEW_FIXPT            0x00000000
#define MOD_OUTPUT3_SELECT_MONOSWSLEW_VALUE            SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_OUTPUT3_SELECT_MONOSWSLEW_TYPE             SIGMASTUDIOTYPE_INTEGER

/* Module output4_select - Mono Switch Nx1*/
#define MOD_OUTPUT4_SELECT_COUNT                       1
#define MOD_OUTPUT4_SELECT_DEVICE                      "IC1"
#define MOD_OUTPUT4_SELECT_MONOSWSLEW_ADDR             54
#define MOD_OUTPUT4_SELECT_MONOSWSLEW_FIXPT            0x00000000
#define MOD_OUTPUT4_SELECT_MONOSWSLEW_VALUE            SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_OUTPUT4_SELECT_MONOSWSLEW_TYPE             SIGMASTUDIOTYPE_INTEGER

#endif
